app:
    resource: "@AppBundle/Controller/"
    type:     annotation

ass:
    resource: "@AssignmentBundle/Resources/config/routing.yml"

front:
    resource: "@FrontBundle/Resources/config/routing.yml"